### ISSUE TITLE
mount volume script is ignored.

### ISSUE THREAD

**Issue by Congrammers** [mrts/docker-postgresql-multiple-databases#2]
based on this issue https://github.com/docker-library/postgres/issues/193

From the readme, the mount volume usage is broken

**Comment by mrts** [comment]
Can you be more specific? What did you do, what happened?

Works well for me, so I would like to get more information.

**Comment by Congrammers** [comment]
My project Directory looks like:
```
.
├── myapp
|  ├── Dockerfile
|  └── script
|     └── docker-posgresql-multiple-databases
│        └── create-multiple-postgresql-databases.sh
└── docker-compose.yml
```

```
db_dev:
    image: postgres:9.6.6
    environment:
      POSTGRES_PASSWORD: mysecretlocalpassword
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: myapp_db_development,myapp_db_test
    volumes:
      - ./myapp/script/docker-posgresql-multiple-databases:/docker-entrypoint-initdb.d
```
So, I want to use it by mounting the script as a volume, when I try to run the docker-compose file. The script within `docker-entrypoint-initdb.d` is ignored. The log returned so:

```
db_dev_1        | server started
db_dev_1        | ALTER ROLE
db_dev_1        | 
db_dev_1        | 
db_dev_1        | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_dev_1        | 
db_dev_1        | waiting for server to shut down....LOG:  received fast shutdown request
db_dev_1        | LOG:  aborting any active transactions
db_dev_1        | LOG:  autovacuum launcher shutting down
db_dev_1        | LOG:  shutting down
db_dev_1        | LOG:  database system is shut down
db_dev_1        |  done
db_dev_1        | server stopped
```

But when I try using it from the image:
```
  db_dev:
    image: postgres-multi-db
    environment:
      POSTGRES_PASSWORD: mysecretlocalpassword
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: myapp_db_development,myapp_db_test
```
building it in-before,
`docker build -t=postgres-multi-db ./aloha/script/docker-postgresql-multiple-databases`; 
it works just fine.


 As explained by **yosifkit** in [here](https://github.com/docker-library/postgres/issues/203#issuecomment-255200501) and [here](https://github.com/docker-library/postgres/issues/193#issuecomment-313803409), the problem stem from the official image itself. I'm looking for a workaround for using the mount volume method instead of building images.
