### ISSUE TITLE
bad interpreter: Permission deniedinterpreter: Permission denied

### ISSUE THREAD

**Issue by emeraldhieu** [mrts/docker-postgresql-multiple-databases#23]
I did the same thing but got permission denied.

```
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - ./postgres-scripts:/docker-entrypoint-initdb.d
```

Error
```
postgres  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/createMultipleDatabases.sh
postgres  | /usr/local/bin/docker-entrypoint.sh: /docker-entrypoint-initdb.d/createMultipleDatabases.sh: /bin/bash: bad interpreter: Permission denied
```
